ARG BASE_CONTAINER=graphblas/python-suitesparse-graphblas:5.1.3.1
FROM ${BASE_CONTAINER}

RUN apt-get update \
    && apt-get install -y graphviz \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /pygraphblas
ADD minimal-requirements.txt /pygraphblas
RUN pip3 install -r minimal-requirements.txt

ADD . /pygraphblas
    
RUN python3 setup.py install
RUN ldconfig
