ARG BASE_CONTAINER=jupyter/minimal-notebook
FROM ${BASE_CONTAINER} as builder
ENV DEBIAN_FRONTEND=noninteractive

USER root

RUN conda install -y graphviz

WORKDIR /home/jovyan
    
ADD . /home/jovyan
    
RUN python setup.py install
RUN pip3 install -r notebook-requirements.txt
RUN chown -R jovyan /home/jovyan

RUN ldconfig
USER jovyan
WORKDIR /home/jovyan/demo
