ARG BASE_CONTAINER=ubuntu:20.04
FROM ${BASE_CONTAINER}

USER root

RUN apt-get update && apt-get install -yq --no-install-recommends \
    build-essential    \
    libsuitesparse-dev \
    python3            \
    python3-pip        \
    libpython3-dev     \
    && rm -rf /var/lib/apt/lists/*

ADD . /pygraphblas
WORKDIR /pygraphblas
    
RUN pip3 install -r minimal-requirements.txt
RUN python3 setup.py clean
RUN python3 setup.py develop
RUN ldconfig
