const double INFINITY = 0.0;  // ... is ints only, so this is a workaround

#define UINT64_MAX ...
#define INT64_MAX ...
#define UINT32_MAX ...
#define INT32_MAX ...
#define UINT16_MAX ...
#define INT16_MAX ...
#define UINT8_MAX ...
#define INT8_MAX ...

#define INT64_MIN ...
#define INT32_MIN ...
#define INT16_MIN ...
#define INT8_MIN ...
