name: Upload Docker Images
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# on:
#   release:
#     types: [created]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: build
      run: |
        VERSION=`python setup.py version | sed -n "s/^.*Version:\s*\(\S*\).*$/\1/p"`
        docker login --username pygraphblas --password ${{ secrets.DOCKERHUB_TOKEN }}
        ./docker_build $VERSION notebook $VERSION clone push
        ./docker_build $VERSION minimal $VERSION clone push
        
